#!/bin/bash
# Check for Commits

# ASCII Coloring
_RED="\e[0;31m"
_CYAN="\e[0;36m"
_YELLOW="\e[0;33m"
_BLUE="\e[0;34m"
_PURPLE="\e[0;35m"
_WHITE="\e[0;37m"
_BOLD="\e[1m"
_RESET="\e[0m"

# Global Variables
_ConfigFile="$HOME/.script_configs/.chkProjects.config"
_Projects=$(cat $_ConfigFile)
_NoDirectories=true
for line in $_Projects
do
	GITBASED=.git
	echo -e "${_WHITE}${_BOLD}Checked Folder:${_RESET} $line"

	# Loop all sub-directories
	for directories in $line*
	do
		if [[ -d $directories ]]; then
			cd $directories
			msg="";

			if [ -d "$GITBASED" ]; then
				test=$(git status);
				# Check Local Repository for changes
				if [[ $test == *"nothing to commit"* ]]; then
					msg="${_CYAN} No Changes "
					# Check if git status has unstaged changes
				elif [[ $test == *"Changes not staged for commit"* ]]; then
					msg="${_YELLOW} Unstaged changes "
					# Check if git status has uncommitted changes
				elif [[ $test == *"Untracked files"* ]]; then
					msg="${_RED} You forgot to commit some files "
				elif [[ $test == *"Changes to be committed"* ]]; then
					msg="${_PURPLE} Staged Changes but not Commited "
				fi

				echo -e "${directories##*/}:$msg${_RESET}"
				cd ..
			fi
			[ $_NoDirectories = true ] && _NoDirectories=false
		fi
	done
	[ $_NoDirectories = true ] && echo -e "${_WHITE}${_BOLD}INFO:${_RESET}${_BLUE} No Directories Found ${_RESET}" || _NoDirectories=true
	echo ""
done
