#!/bin/bash
#create git repo if not existent

GIT='/mnt/git/'
REPO=$1
GitRepo="$GIT$REPO.git"

[[ ! -d "$GitRepo" ]] && mkdir "$GitRepo" &&
  cd $GitRepo && git init --bare ||
  echo 'Git Repository already exists'
